# Vaibhav Kishor Lokhande
# Batch:B2
# Roll no:37
# Pract no 4: Generating the n gram model using nltk



from nltk import ngrams

from nltk.util import ngrams
#unigram model

n = 1
sentence = 'If you are consistently active, you probably feel strong, healthy and at times utterly invincible. This can make it doubly painful when your body does succumb to illness which, let’s face it, happens to the best of us. Not only do you feel icky when you’re sick, but you’re also discouraged from doing the one thing that makes you feel great: exercise.'
unigrams = ngrams(sentence.split(), n)
print("Unigram Model\n")


for item in unigrams:
    print(item)
print("\n\n")
#bigram model
n = 2
sentence = 'If you are consistently active, you probably feel strong, healthy and at times utterly invincible. This can make it doubly painful when your body does succumb to illness which, let’s face it, happens to the best of us. Not only do you feel icky when you’re sick, but you’re also discouraged from doing the one thing that makes you feel great: exercise.'
unigrams = ngrams(sentence.split(), n)
print("Bigram Model\n")
for item in unigrams:
    print(item)
print("\n\n")
#trigram model
n = 3
sentence = 'If you are consistently active, you probably feel strong, healthy and at times utterly invincible. This can make it doubly painful when your body does succumb to illness which, let’s face it, happens to the best of us. Not only do you feel icky when you’re sick, but you’re also discouraged from doing the one thing that makes you feel great: exercise.'
unigrams = ngrams(sentence.split(), n)
print("Trigram Model\n")

for item in unigrams:
    print(item)
print("\n\n\n")


print("Trigram Model With Text File")

#using text file input
from nltk import ngrams
file = open("/home/exam/NLP_LAB/Assignment_NO_4.txt")
for i in file.readlines():
    cumulative = i
    sentences = i.split(".")
    counter = 0
    for sentence in sentences:
        print("For sentence", counter + 1, ", trigrams are: ")
        trigrams = ngrams(sentence.split(" "), 3)
        for grams in trigrams:
            print(grams)
        counter += 1
        print()
        
 #output    
'''
Unigram Model

('If',)
('you',)
('are',)
('consistently',)
('active,',)
('you',)
('probably',)
('feel',)
('strong,',)
('healthy',)
('and',)
('at',)
('times',)
('utterly',)
('invincible.',)
('This',)
('can',)
('make',)
('it',)
('doubly',)
('painful',)
('when',)
('your',)
('body',)
('does',)
('succumb',)
('to',)
('illness',)
('which,',)
('let’s',)
('face',)
('it,',)
('happens',)
('to',)
('the',)
('best',)
('of',)
('us.',)
('Not',)
('only',)
('do',)
('you',)
('feel',)
('icky',)
('when',)
('you’re',)
('sick,',)
('but',)
('you’re',)
('also',)
('discouraged',)
('from',)
('doing',)
('the',)
('one',)
('thing',)
('that',)
('makes',)
('you',)
('feel',)
('great:',)
('exercise.',)



Bigram Model

('If', 'you')
('you', 'are')
('are', 'consistently')
('consistently', 'active,')
('active,', 'you')
('you', 'probably')
('probably', 'feel')
('feel', 'strong,')
('strong,', 'healthy')
('healthy', 'and')
('and', 'at')
('at', 'times')
('times', 'utterly')
('utterly', 'invincible.')
('invincible.', 'This')
('This', 'can')
('can', 'make')
('make', 'it')
('it', 'doubly')
('doubly', 'painful')
('painful', 'when')
('when', 'your')
('your', 'body')
('body', 'does')
('does', 'succumb')
('succumb', 'to')
('to', 'illness')
('illness', 'which,')
('which,', 'let’s')
('let’s', 'face')
('face', 'it,')
('it,', 'happens')
('happens', 'to')
('to', 'the')
('the', 'best')
('best', 'of')
('of', 'us.')
('us.', 'Not')
('Not', 'only')
('only', 'do')
('do', 'you')
('you', 'feel')
('feel', 'icky')
('icky', 'when')
('when', 'you’re')
('you’re', 'sick,')
('sick,', 'but')
('but', 'you’re')
('you’re', 'also')
('also', 'discouraged')
('discouraged', 'from')
('from', 'doing')
('doing', 'the')
('the', 'one')
('one', 'thing')
('thing', 'that')
('that', 'makes')
('makes', 'you')
('you', 'feel')
('feel', 'great:')
('great:', 'exercise.')



Trigram Model

('If', 'you', 'are')
('you', 'are', 'consistently')
('are', 'consistently', 'active,')
('consistently', 'active,', 'you')
('active,', 'you', 'probably')
('you', 'probably', 'feel')
('probably', 'feel', 'strong,')
('feel', 'strong,', 'healthy')
('strong,', 'healthy', 'and')
('healthy', 'and', 'at')
('and', 'at', 'times')
('at', 'times', 'utterly')
('times', 'utterly', 'invincible.')
('utterly', 'invincible.', 'This')
('invincible.', 'This', 'can')
('This', 'can', 'make')
('can', 'make', 'it')
('make', 'it', 'doubly')
('it', 'doubly', 'painful')
('doubly', 'painful', 'when')
('painful', 'when', 'your')
('when', 'your', 'body')
('your', 'body', 'does')
('body', 'does', 'succumb')
('does', 'succumb', 'to')
('succumb', 'to', 'illness')
('to', 'illness', 'which,')
('illness', 'which,', 'let’s')
('which,', 'let’s', 'face')
('let’s', 'face', 'it,')
('face', 'it,', 'happens')
('it,', 'happens', 'to')
('happens', 'to', 'the')
('to', 'the', 'best')
('the', 'best', 'of')
('best', 'of', 'us.')
('of', 'us.', 'Not')
('us.', 'Not', 'only')
('Not', 'only', 'do')
('only', 'do', 'you')
('do', 'you', 'feel')
('you', 'feel', 'icky')
('feel', 'icky', 'when')
('icky', 'when', 'you’re')
('when', 'you’re', 'sick,')
('you’re', 'sick,', 'but')
('sick,', 'but', 'you’re')
('but', 'you’re', 'also')
('you’re', 'also', 'discouraged')
('also', 'discouraged', 'from')
('discouraged', 'from', 'doing')
('from', 'doing', 'the')
('doing', 'the', 'one')
('the', 'one', 'thing')
('one', 'thing', 'that')
('thing', 'that', 'makes')
('that', 'makes', 'you')
('makes', 'you', 'feel')
('you', 'feel', 'great:')
('feel', 'great:', 'exercise.')




Trigram Model With Text File
For sentence 1 , trigrams are: 
('There', 'are', 'a')
('are', 'a', 'number')
('a', 'number', 'of')
('number', 'of', 'infections')
('of', 'infections', 'we')
('infections', 'we', 'can')
('we', 'can', 'pick')
('can', 'pick', 'up')
('pick', 'up', 'throughout')
('up', 'throughout', 'the')
('throughout', 'the', 'year,')
('the', 'year,', 'some')
('year,', 'some', 'worse')
('some', 'worse', 'than')
('worse', 'than', 'others')

For sentence 2 , trigrams are: 
('', 'While', 'we’ve')
('While', 'we’ve', 'always')
('we’ve', 'always', 'been')
('always', 'been', 'told')
('been', 'told', 'to')
('told', 'to', 'avoid')
('to', 'avoid', 'working')
('avoid', 'working', 'out')
('working', 'out', 'while')
('out', 'while', 'sick,')
('while', 'sick,', 'it’s')
('sick,', 'it’s', 'tempting')
('it’s', 'tempting', 'to')
('tempting', 'to', 'ask')
('to', 'ask', 'how')
('ask', 'how', 'sick')
('how', 'sick', 'is')
('sick', 'is', 'sick,')
('is', 'sick,', 'and')
('sick,', 'and', 'what')
('and', 'what', 'counts')
('what', 'counts', 'as')
('counts', 'as', '“working')
('as', '“working', 'out”?')
('“working', 'out”?', 'Is')
('out”?', 'Is', 'a')
('Is', 'a', 'light')
('a', 'light', 'walk')
('light', 'walk', 'OK,')
('walk', 'OK,', 'or')
('OK,', 'or', 'should')
('or', 'should', 'you')
('should', 'you', 'avoid')
('you', 'avoid', 'any')
('avoid', 'any', 'activity')
('any', 'activity', 'altogether?')
('activity', 'altogether?', 'Can')
('altogether?', 'Can', 'you')
('Can', 'you', 'do')
('you', 'do', 'weights')
('do', 'weights', 'at')
('weights', 'at', 'home?')
('at', 'home?', 'Here’s')
('home?', 'Here’s', 'the')
('Here’s', 'the', 'real')
('the', 'real', 'question:')
('real', 'question:', 'When')
('question:', 'When', '(if')
('When', '(if', 'ever)')
('(if', 'ever)', 'is')
('ever)', 'is', 'it')
('is', 'it', 'OK')
('it', 'OK', 'to')
('OK', 'to', 'exercise')
('to', 'exercise', 'while')
('exercise', 'while', 'you’re')
('while', 'you’re', 'sick?\n')

For sentence 1 , trigrams are: 

For sentence 1 , trigrams are: 

For sentence 1 , trigrams are: 
('As', 'it', 'turns')
('it', 'turns', 'out,')
('turns', 'out,', 'the')
('out,', 'the', 'question')
('the', 'question', 'of')
('question', 'of', 'whether')
('of', 'whether', 'you')
('whether', 'you', 'should')
('you', 'should', 'work')
('should', 'work', 'out')
('work', 'out', 'while')
('out', 'while', 'sick')
('while', 'sick', 'may')
('sick', 'may', 'depend')
('may', 'depend', 'on')
('depend', 'on', 'what')
('on', 'what', 'you’re')
('what', 'you’re', 'sick')
('you’re', 'sick', 'with')
('sick', 'with', 'and')
('with', 'and', 'the')
('and', 'the', 'severity')
('the', 'severity', 'of')
('severity', 'of', 'your')
('of', 'your', 'symptoms')

For sentence 2 , trigrams are: 
('', 'While', 'a')
('While', 'a', 'fever')
('a', 'fever', 'and')
('fever', 'and', 'upset')
('and', 'upset', 'stomach')
('upset', 'stomach', 'would')
('stomach', 'would', 'stop')
('would', 'stop', 'most')
('stop', 'most', 'of')
('most', 'of', 'us')
('of', 'us', 'from')
('us', 'from', 'even')
('from', 'even', 'thinking')
('even', 'thinking', 'about')
('thinking', 'about', 'touching')
('about', 'touching', 'a')
('touching', 'a', 'weight,')
('a', 'weight,', 'a')
('weight,', 'a', 'stuffy')
('a', 'stuffy', 'nose')
('stuffy', 'nose', 'and')
('nose', 'and', 'headache')
('and', 'headache', 'might')
('headache', 'might', 'actually')
('might', 'actually', 'benefit')
('actually', 'benefit', 'from')
('benefit', 'from', 'a')
('from', 'a', 'few')
('a', 'few', 'minutes')
('few', 'minutes', 'of')
('minutes', 'of', 'movement')

For sentence 3 , trigrams are: 
('', 'Here’s', 'what')
('Here’s', 'what', 'you')
('what', 'you', 'need')
('you', 'need', 'to')
('need', 'to', 'know')
('to', 'know', 'to')
('know', 'to', 'decide')
('to', 'decide', 'whether')
('decide', 'whether', 'you')
('whether', 'you', 'should')
('you', 'should', 'be')
('should', 'be', 'working')
('be', 'working', 'out')
('working', 'out', 'while')
('out', 'while', 'sick')'''